#!/usr/bin/env node
// tool/ui_kit_shots/gen.mjs — regenerate every hand-drifted artifact from registry.mjs (the SSOT).
//
// Regenerates:
//   • index.html            — the `const SCREENS = [ … ]` gallery array
//   • specs/INDEX.md         — the screen/state manifest table
//   • shots/INDEX.md         — the canonical-PNG manifest
//
// Usage: node tool/ui_kit_shots/gen.mjs   (or: npm run gen:ui-kit)
// It only writes when content changes; prints what it touched. Pair with verify.mjs, which
// FAILS if these files ever drift from the registry again.

import { readFile, writeFile } from 'node:fs/promises';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SCREENS, totals } from './registry.mjs';

const KIT = fileURLToPath(new URL('../../docs/design/MemoX Design System_v4/ui_kits/memox-app/', import.meta.url));
const INDEX_HTML = KIT + 'index.html';
const SPECS_INDEX = KIT + 'specs/INDEX.md';
const SHOTS_INDEX = KIT + 'shots/INDEX.md';
const SPECS_DIR = KIT + 'specs/';

// ---- screen source resolution + component-map derivation (contract §3, auto — never hand-kept) ----
function jsxCache() {
  const roots = ['_features', '_shared'].map((r) => join(KIT, r));
  const files = [];
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith('.jsx')) files.push(p);
    }
  };
  roots.forEach(walk);
  return files.map((f) => ({ f, src: readFileSync(f, 'utf8') }));
}
const CACHE = jsxCache();
function resolveSrc(group) {
  const hit = CACHE.find((x) => new RegExp('window\\.' + group + '\\s*=').test(x.src) && !x.f.replace(/\\/g, '/').includes('/components/'));
  return hit || null;
}
function deriveComponents(src, group) {
  const mx = [...src.matchAll(/\bMx[A-Z][A-Za-z]+/g)].map((m) => m[0]);
  const win = [...src.matchAll(/window\.([A-Z][A-Za-z]+)/g)].map((m) => m[1])
    .filter((n) => n !== group && !/^MemoX/.test(n)) // drop the namespace + the screen's own self-registration
    .map((n) => 'window.' + n);
  return [...new Set([...mx, ...win])].sort();
}
const kitFwd = KIT.replace(/\\/g, '/');
const relSrc = (f) => '../' + f.replace(/\\/g, '/').replace(kitFwd, '');
function appBarOf(src) {
  const m = src.match(/variant=["']([a-z]+)["']/);
  if (m) return `${m[1]} MxContextualAppBar`;
  if (/\bMxBottomNav\b/.test(src)) return 'root MxContextualAppBar + bottom nav';
  return 'MxContextualAppBar';
}

const AUTOGEN = 'AUTOGENERATED from tool/ui_kit_shots/registry.mjs — do not hand-edit; run `npm run gen:ui-kit`.';

// ---- index.html gallery array ----
function galleryBlock() {
  const rows = SCREENS.map((s) => {
    const note = s.note ? `  // ${note_esc(s.note)}\n` : '';
    const states = s.states.map((x) => `'${x}'`).join(', ');
    return `${note}  { id: '${s.id}', title: '${title_esc(s.title)}', Comp: () => window.${s.group}, states: [${states}] },`;
  }).join('\n');
  return `const SCREENS = [\n${rows}\n];`;
}
const note_esc = (s) => s.replace(/\r?\n/g, ' ');
const title_esc = (s) => s.replace(/'/g, "\\'");

async function genGallery() {
  const src = await readFile(INDEX_HTML, 'utf8');
  const re = /const SCREENS = \[[\s\S]*?\n\];/;
  if (!re.test(src)) throw new Error('gallery: `const SCREENS = [ … ];` block not found in index.html');
  const marker = `// ${AUTOGEN}\n`;
  // keep any existing autogen marker line from doubling up
  const next = src.replace(new RegExp('(?:// AUTOGENERATED[^\\n]*\\n)?const SCREENS = \\[[\\s\\S]*?\\n\\];'), marker + galleryBlock());
  return [INDEX_HTML, next];
}

// ---- specs/INDEX.md ----
function specsIndex() {
  const specced = SCREENS.filter((s) => s.spec !== false); // app-bar etc. are galleries, not screen specs
  const rows = specced.map((s) => `| ${s.id} | ${s.title} | \`${s.id}.md\` | ${s.states.length} |`).join('\n');
  const t = { screens: specced.length, states: specced.reduce((a, s) => a + s.states.length, 0) };
  return `# UI Kit Screen Specs — Manifest

> ${AUTOGEN}
> Each \`<id>.md\` is generated with the contract artifacts (objective, archetype, composition +
> component map, state matrix); the component map is auto-derived from the screen \`*.jsx\`, which
> together with the canonical PNGs in \`../shots/\` stays the source of truth for pixel composition.
> This index can never again claim a screen the registry doesn't have.

| ID | Screen | Spec file | States |
| --- | --- | --- | --- |
${rows}

Total: ${t.screens} screens · ${t.states} states.
`;
}

// ---- shots/INDEX.md ----
function shotsIndex() {
  const sections = SCREENS.map((s) => {
    const rows = s.states.map((st) => `| ${st.replace(/-/g, ' ')} | \`${s.id}--${st}--light.png\` | \`${s.id}--${st}--dark.png\` |`).join('\n');
    return `## ${s.id} — ${s.title}\n\n| State | Light | Dark |\n| --- | --- | --- |\n${rows}`;
  }).join('\n\n');
  const t = totals();
  return `# UI Kit Screenshots — Manifest

> ${AUTOGEN}

The canonical visual reference: every screen state ships as a light + dark PNG pair at 390px width
(\`<screen-id>--<state>--<theme>.png\`) under this folder. Read the PNG, not the kit JSX. The images
are rendered by \`tool/ui_kit_shots/shoot.mjs\`; this index is generated from the registry so it
always matches the ${t.states}-state matrix (${t.screens} screens).

${sections}
`;
}

// ---- per-screen spec (contract artifacts 1-3, 6) ----
function screenSpec(s) {
  const rel = `${s.id}.md`;
  const hit = resolveSrc(s.group);
  const src = hit ? relSrc(hit.f) : `(source for window.${s.group} not found)`;
  const comps = hit ? deriveComponents(hit.src, s.group).map((c) => `\`${c}\``).join(', ') : '_n/a_';
  const bar = hit ? appBarOf(hit.src) : 'MxContextualAppBar';
  const cta = s.cta ? `**${s.cta}**` : '_none — a read / navigation surface (no competing CTA)_';
  const stateRows = s.states.map((st, i) => `| ${i + 1} | \`${st}\` |`).join('\n');
  return [SPECS_DIR + rel, `# ${s.id} — ${s.title} — screen spec

> ${AUTOGEN}
> Source of truth: \`${src}\`; reference PNGs \`../shots/${s.id}--<state>--<theme>.png\` (390×780).
> Verify: \`node tool/ui_kit_shots/shoot.mjs ${s.id}\` (gated by \`npm run verify:ui-kit\`).

## Objective (contract §1)

${s.objective}

Primary CTA: ${cta}

## Archetype (contract §2)

${s.archetype}

## Composition map (contract §3)

Top → bottom: **${bar}** → primary content → ${s.cta ? `primary action (${s.cta})` : 'no primary action'}.
Exact layout order is owned by the source (\`${src}\`) and the reference PNGs — read those for pixel
composition; the component map below is the authoritative set of pieces in play.

## Component map (contract §3) — auto-derived from source

${comps}

## State matrix (contract §6) — ${s.states.length} states, each rendered light + dark

| # | state |
| --- | --- |
${stateRows}

## Handoff notes

Spacing scale \`{4,8,12,16,24,32,48}\`; screen padding 16; tokens only (no raw hex / off-scale).
Exactly one primary objective; touch targets ≥ 44×44. This spec is generated from
\`tool/ui_kit_shots/registry.mjs\` — edit the registry, not this file.
`];
}

async function main() {
  const check = process.argv.includes('--check');
  const specJobs = SCREENS.filter((s) => s.spec !== false).map(screenSpec);
  const jobs = [await genGallery(), [SPECS_INDEX, specsIndex()], [SHOTS_INDEX, shotsIndex()], ...specJobs];
  let changed = 0;
  const drifted = [];
  const eol = (s) => (s == null ? s : s.replace(/\r\n/g, '\n')); // git autocrlf checks files out CRLF; compare LF-normalized so the gate never false-drifts
  for (const [path, next] of jobs) {
    const prev = await readFile(path, 'utf8').catch(() => null);
    if (eol(prev) === eol(next)) { console.log('  =', rel(path)); continue; }
    if (check) { drifted.push(rel(path)); console.log('  ✗', rel(path), '(drifted from registry)'); continue; }
    await writeFile(path, next);
    console.log('  ✎', rel(path));
    changed++;
  }
  const t = totals();
  if (check) {
    if (drifted.length) {
      console.error(`\n✗ DRIFT — ${drifted.length} artifact(s) out of sync with registry.mjs: ${drifted.join(', ')}`);
      console.error('  Run `npm run gen:ui-kit` and commit the result.');
      process.exit(1);
    }
    console.log(`\n✓ IN SYNC — gallery + specs/INDEX + shots/INDEX + ${SCREENS.filter((s) => s.spec !== false).length} screen specs match the registry (${t.screens} screens / ${t.states} states).`);
    return;
  }
  console.log(`gen:ui-kit — ${changed} file(s) written · ${t.screens} screens / ${t.states} states / ${t.sample} sampled`);
}
const rel = (p) => p.split(/[/\\]/).slice(-2).join('/');
main().catch((e) => { console.error('gen:ui-kit FAILED:', e.message); process.exit(1); });
