#!/usr/bin/env node
// tool/ui_kit_shots/gen.mjs — regenerate every hand-drifted artifact from registry.mjs (the SSOT).
//
// Regenerates:
//   • index.html            — the `const SCREENS = [ … ]` gallery array
//   • specs/INDEX.md         — the screen/state manifest table
//   • shots/INDEX.md         — the canonical-PNG manifest
//
// Usage: node tool/ui_kit_shots/gen.mjs   (or: npm run gen:ui-kit)
// It only writes when content changes; prints what it touched. Pair with verify.mjs, which
// FAILS if these files ever drift from the registry again.

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { SCREENS, totals } from './registry.mjs';

const KIT = fileURLToPath(new URL('../../docs/design/MemoX Design System_v4/ui_kits/memox-app/', import.meta.url));
const INDEX_HTML = KIT + 'index.html';
const SPECS_INDEX = KIT + 'specs/INDEX.md';
const SHOTS_INDEX = KIT + 'shots/INDEX.md';

const AUTOGEN = 'AUTOGENERATED from tool/ui_kit_shots/registry.mjs — do not hand-edit; run `npm run gen:ui-kit`.';

// ---- index.html gallery array ----
function galleryBlock() {
  const rows = SCREENS.map((s) => {
    const note = s.note ? `  // ${note_esc(s.note)}\n` : '';
    const states = s.states.map((x) => `'${x}'`).join(', ');
    return `${note}  { id: '${s.id}', title: '${title_esc(s.title)}', Comp: () => window.${s.group}, states: [${states}] },`;
  }).join('\n');
  return `const SCREENS = [\n${rows}\n];`;
}
const note_esc = (s) => s.replace(/\r?\n/g, ' ');
const title_esc = (s) => s.replace(/'/g, "\\'");

async function genGallery() {
  const src = await readFile(INDEX_HTML, 'utf8');
  const re = /const SCREENS = \[[\s\S]*?\n\];/;
  if (!re.test(src)) throw new Error('gallery: `const SCREENS = [ … ];` block not found in index.html');
  const marker = `// ${AUTOGEN}\n`;
  // keep any existing autogen marker line from doubling up
  const next = src.replace(new RegExp('(?:// AUTOGENERATED[^\\n]*\\n)?const SCREENS = \\[[\\s\\S]*?\\n\\];'), marker + galleryBlock());
  return [INDEX_HTML, next];
}

// ---- specs/INDEX.md ----
function specsIndex() {
  const specced = SCREENS.filter((s) => s.spec !== false); // app-bar etc. are galleries, not screen specs
  const rows = specced.map((s) => `| ${s.id} | ${s.title} | \`${s.id}.md\` | ${s.states.length} |`).join('\n');
  const t = { screens: specced.length, states: specced.reduce((a, s) => a + s.states.length, 0) };
  return `# UI Kit Screen Specs — Manifest

> ${AUTOGEN}
> The DOM-dump exporter and freshness gate that once produced per-node specs are gone; specs are
> now hand-maintained structural specs (source of truth: each screen \`*.jsx\` + the canonical PNGs
> in \`../shots/\`). This index, however, is generated — it can never again claim a screen the
> registry doesn't have.

| ID | Screen | Spec file | States |
| --- | --- | --- | --- |
${rows}

Total: ${t.screens} screens · ${t.states} states.
`;
}

// ---- shots/INDEX.md ----
function shotsIndex() {
  const sections = SCREENS.map((s) => {
    const rows = s.states.map((st) => `| ${st.replace(/-/g, ' ')} | \`${s.id}--${st}--light.png\` | \`${s.id}--${st}--dark.png\` |`).join('\n');
    return `## ${s.id} — ${s.title}\n\n| State | Light | Dark |\n| --- | --- | --- |\n${rows}`;
  }).join('\n\n');
  const t = totals();
  return `# UI Kit Screenshots — Manifest

> ${AUTOGEN}

The canonical visual reference: every screen state ships as a light + dark PNG pair at 390px width
(\`<screen-id>--<state>--<theme>.png\`) under this folder. Read the PNG, not the kit JSX. The images
are rendered by \`tool/ui_kit_shots/shoot.mjs\`; this index is generated from the registry so it
always matches the ${t.states}-state matrix (${t.screens} screens).

${sections}
`;
}

async function main() {
  const check = process.argv.includes('--check');
  const jobs = [await genGallery(), [SPECS_INDEX, specsIndex()], [SHOTS_INDEX, shotsIndex()]];
  let changed = 0;
  const drifted = [];
  for (const [path, next] of jobs) {
    const prev = await readFile(path, 'utf8').catch(() => null);
    if (prev === next) { console.log('  =', rel(path)); continue; }
    if (check) { drifted.push(rel(path)); console.log('  ✗', rel(path), '(drifted from registry)'); continue; }
    await writeFile(path, next);
    console.log('  ✎', rel(path));
    changed++;
  }
  const t = totals();
  if (check) {
    if (drifted.length) {
      console.error(`\n✗ DRIFT — ${drifted.length} artifact(s) out of sync with registry.mjs: ${drifted.join(', ')}`);
      console.error('  Run `npm run gen:ui-kit` and commit the result.');
      process.exit(1);
    }
    console.log(`\n✓ IN SYNC — gallery + specs/INDEX + shots/INDEX match the registry (${t.screens} screens / ${t.states} states).`);
    return;
  }
  console.log(`gen:ui-kit — ${changed} file(s) written · ${t.screens} screens / ${t.states} states / ${t.sample} sampled`);
}
const rel = (p) => p.split(/[/\\]/).slice(-2).join('/');
main().catch((e) => { console.error('gen:ui-kit FAILED:', e.message); process.exit(1); });
