/**
 * Material Symbols Rounded glyph map (WBS 1.4) — GENERATED.
 *
 * name → the Private-Use-Area codepoint char, rendered in the bundled
 * `MaterialSymbolsRounded` font (subset to the kit's glyph set). Icons render
 * by CODEPOINT, not ligature — ligatures are unreliable in RN Text.
 * Regenerate by re-subsetting the font from the kit's icon usage.
 */

export const GLYPHS = {
  account_tree: '\ue97a',
  add: '\ue145',
  add_circle: '\ue990',
  apps: '\ue5c3',
  arrow_back: '\ue5c4',
  arrow_downward: '\ue5db',
  arrow_forward: '\ue5c8',
  backup: '\ue864',
  bar_chart: '\ue26b',
  biotech: '\uea3a',
  bolt: '\uea0b',
  celebration: '\uea65',
  check: '\ue5ca',
  check_box: '\ue834',
  check_box_outline_blank: '\ue835',
  check_circle: '\uf0be',
  chevron_left: '\ue5cb',
  chevron_right: '\ue5cc',
  close: '\ue5cd',
  cloud_done: '\ue2bf',
  cloud_off: '\ue2c1',
  cloud_sync: '\ueb5a',
  content_copy: '\ue14d',
  content_paste: '\ue14f',
  dashboard_customize: '\ue99b',
  delete: '\ue92e',
  description: '\ue873',
  directions: '\ue52e',
  diversity_3: '\uf8d9',
  done_all: '\ue877',
  download: '\uf090',
  drive_file_move: '\ue9a1',
  edit: '\uf097',
  error: '\uf8b6',
  error_outline: '\uf8b6',
  expand_less: '\ue5ce',
  expand_more: '\ue5cf',
  explore: '\ue87a',
  favorite: '\ue87e',
  filter_5: '\ue3d5',
  folder: '\ue2c7',
  format_shapes: '\ue25e',
  format_size: '\ue245',
  functions: '\ue24a',
  grid_view: '\ue9b0',
  headphones: '\uf01f',
  history: '\ue8b3',
  history_edu: '\uea3e',
  home: '\ue9b2',
  hourglass_empty: '\ue88b',
  info: '\ue88e',
  insights: '\uf092',
  ios_share: '\ue6b8',
  join_inner: '\ueaf4',
  keyboard: '\ue312',
  language: '\uea07',
  library_add: '\ue03c',
  library_music: '\ue030',
  lightbulb: '\ue90f',
  local_fire_department: '\uef55',
  login: '\uea77',
  logout: '\ue9ba',
  menu_book: '\uea19',
  merge_type: '\ue252',
  mic: '\ue31d',
  more_vert: '\ue5d4',
  north_west: '\uf1e2',
  note_add: '\ue89c',
  notifications: '\ue7f5',
  notifications_active: '\ue7f7',
  numbers: '\ueac7',
  open_in_new: '\ue89e',
  palette: '\ue40a',
  pause: '\ue034',
  person: '\uf0d3',
  play_arrow: '\ue037',
  play_circle: '\ue1c4',
  play_disabled: '\uef6a',
  playing_cards: '\uf5dc',
  psychology: '\uea4a',
  quiz: '\uf04c',
  radio_button_checked: '\ue837',
  radio_button_unchecked: '\ue836',
  record_voice_over: '\ue91f',
  refresh: '\ue5d5',
  replay: '\ue042',
  restart_alt: '\uf053',
  restaurant: '\ue56c',
  save_alt: '\uf090',
  schedule: '\uefd6',
  school: '\ue80c',
  search: '\uef7a',
  search_off: '\uea76',
  select_all: '\ue162',
  sell: '\uf05b',
  share: '\ue80d',
  shuffle: '\ue043',
  skip_next: '\ue044',
  skip_previous: '\ue045',
  sort_by_alpha: '\ue053',
  speed: '\ue9e4',
  spellcheck: '\ue8ce',
  sports_esports: '\uea28',
  stacks: '\uf500',
  style: '\ue41d',
  swap_vert: '\ue8d5',
  sync: '\ue627',
  sync_problem: '\ue629',
  table_chart: '\ue265',
  task_alt: '\ue2e6',
  text_fields: '\ue262',
  timeline: '\ue922',
  today: '\ue8df',
  translate: '\ue8e2',
  travel_explore: '\ue2db',
  trending_up: '\ue8e5',
  tune: '\ue429',
  upload_file: '\ue9fc',
  verified: '\uef76',
  visibility: '\ue8f4',
  visibility_off: '\ue8f5',
  volume_off: '\ue04f',
  volume_up: '\ue050',
  warning: '\uf083',
  waving_hand: '\ue766',
  widgets: '\ue1bd',
  work: '\ue943',
} as const;

export type IconName = keyof typeof GLYPHS;

/** Deterministic fallback rendered when an unknown icon name is requested. */
export const FALLBACK_ICON: IconName = 'error_outline';
